## ---------------------------
##
## Script name: process_veg_coords
##
## Purpose of script: Take the coordinates from the wetland vegetation sampling
##  and convert them from degrees, minutes, seconds to decimal degrees. 
##
## Author: Samuel Woodman
##
## Date Created: 2023-11-06
##
## Email: samuel.woodman@gmail.com
##
## ---------------------------
##
## Notes: Input xlsx was generated by Oshini after she weighed the samples. 
##        Changes made in Excel include replace • with degree symbol, renaming
##        columns, removing double spaces, adding missing sample numbers 
##        (arbitrary). 
##   
##
## ---------------------------

options(scipen = 6, digits = 10)

# Load packages -----------------------------------------------------------

library(tidyverse)
library(here)
library(readxl)
library(sf)


# Functions ---------------------------------------------------------------

# Function to convert DMS to DD
# Generated using ChatGPT
convert_dms_to_dd <- function(degrees, minutes, seconds, direction) {
  dd <- degrees + minutes/60 + seconds/3600
  if (toupper(direction) %in% c("S", "W")) {
    dd <- -dd
  }
  return(dd)
}

# Load data ---------------------------------------------------------------

veg_df <- read_xlsx(here("data/raw/veg_biomass.xlsx")) 

# Process data ------------------------------------------------------------

## Subset df to extract only samples with decimal degrees
df_dd <- veg_df %>% 
  # degree symbol only present in dms 
  filter(!str_detect(latitude_N, "°")) %>% 
  # rename for row bind
  rename(lat = latitude_N, 
         lon = longitude_W) %>% 
  # convert to numeric
  mutate(lat = as.numeric(lat), 
         lon = as.numeric(lon)*-1)

## Subset and process data with DMS as lat/lan
df_dms <- veg_df %>% 
  # degree symbol only present in dms 
  filter(str_detect(latitude_N, "°")) %>% 
  # Use Regex to select only the numeric component of DMS
  # https://stackoverflow.com/questions/18321779/degrees-minutes-and-seconds-regex
  separate_wider_regex(latitude_N, 
                       c(lat_deg = "\\d+",
                         "\\s?°\\s?",
                         lat_min = "\\d+",
                         "\\s?'\\s?",
                         lat_sec = "\\d+",
                         "\"")) %>% 
  separate_wider_regex(longitude_W, 
                       c(lon_deg = "\\d+",
                         "\\s?°\\s?",
                         lon_min = "\\d+",
                         "\\s?'\\s?",
                         lon_sec = "\\d+",
                         "\"")) %>% 
  # convert lat lon to numberic
  mutate(across(starts_with(c("lat", "lon")), as.numeric)) %>% 
  # convert DMS to DD
  mutate(lat = convert_dms_to_dd(lat_deg, lat_min, lat_sec, "N"),
         lon = convert_dms_to_dd(lon_deg, lon_min, lon_sec, "W")) %>% 
  # remove degree, minute, second columns
  select(-starts_with(c("lat_", "lon_")))

bind_rows(df_dms, df_dd) %>% view

## Convert to spatial df
veg_coord_df <- bind_rows(df_dms, df_dd) %>% # bind dms and dd dfs
  # convert to sf 
  st_as_sf(., coords = c("lon", "lat"),
           crs = 4326) 


# Save output -------------------------------------------------------------

veg_coord_df %>% 
  st_write(., here("data/processed/veg_coords.gpkg"), 
           overwrite = T, delete_dsn = TRUE)


